pipeline {
    agent any
         tools {nodejs "NODEJS"} 
    

     
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
          
         
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('SonarQube Analysis'){
            steps {
                
                withSonarQubeEnv('sonarqube'){
                    
                        -D sonar.login=admin \
                        -D sonar.password=admin \
                        -D sonar.projectKey=test \
                        -D sonar.javabinaries=src \
                        -D sonar.host.url=http://localhost:9000/"
                }
                
            }
        }
}

