pipeline {
    agent any
         tools {nodejs "NODEJS"} 
    

     
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
          
         
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
node{
        stage('SonarQube Analysis'){
        def scannerHome = tool 'sonarqube';
        withSonarQubeEnv('sonarqube'){
            sh "${scannerHome}/bin/sonar-scanner \
            -D sonar.login=admin \
            -D sonar.password=admin \
            -D sonar.projectKey=test \
            -D sonar.host.url=http://localhost:9000/"
            
        }
        }
     }
}
}
